### ISSUE TITLE
DP83869HM: 1000BASE-X: Auto neg not disabled in linux driver dp83869.c

### ISSUE THREAD

**Issue by ninousf** [TexasInstruments/ti-ethernet-software#1]
Hi

According to dp83869hm datasheet, in 9.4.2.1:

> In fiber mode, the speed is not decided through auto-negotiation. Both sides of the link must be configured to the same operating speed.

But if i look at the driver code, the auto negotiation seems disabled only for 100BASE_FX:

https://github.com/TexasInstruments/ti-ethernet-software/blob/a79de01bb7b7b114d6f9be1fa9d467f89d9f1227/linux_drivers/dp83869.c#L659

Is there an explanation ?

because, in my project, i had to make a patch disabling auto-neg for 1000BASE-X, in order to have a working link.

**Comment by a-reyes-TI** [comment]
Hi Ninousf,

I believe I spoke with you on E2E: [https://e2e.ti.com/support/interface-group/interface/f/interface-forum/1349643/dp83869hm-1000base-x-auto-neg-not-disabled-in-linux-driver-dp83869-c](url) 

You are correct, both speeds should have auto-negotiation disabled. In the E2E thread linked above I provided an updated version of the driver, was your patch similar?

**Comment by ninousf** [comment]
hi
yes, my patch is exactly the same ;)
