### ISSUE TITLE
DP83TG720: Integrate with Aurix mcu

### ISSUE THREAD

**Issue by avinashk15** [TexasInstruments/ti-ethernet-software#2]
I am using Dp83tg720 with Aurix microcontroller. The RTOS driver is using follwing header files which seems to be TI specific. Where can I find these files or Is there a **integration document** ?

_#include <ti/drv/enet/include/core/enet_utils.h>
#include <ti/drv/enet/priv/core/enet_trace_priv.h>
#include <ti/drv/enet/include/phy/enetphy.h>
#include <ti/drv/enet/include/phy/dp83tg720.h>_

**Comment by e-mayhew** [comment]
Hi,
Can you share which SDK you are using with Aurix MCU? 
We currently do not have any resources for RTOS integration with non-TI SDKs, but I can help review and compare relevant functions/header files.

**Comment by avinashk15** [comment]
Hi,
I am using autosar MCAL Ethernet interface.

**Comment by e-mayhew** [comment]
We unfortunately do not have drivers or integration collateral for AutoSAR environment, this will have to be ported manually.

**Comment by avinashk15** [comment]
Thank you for the confirmation.
